spring.application.name=sbiyonoproject
spring.datasource.username=root
spring.datasource.password=ss108036**
spring.datasource.url=jdbc:mysql://localhost:3306/Spring
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true